### ISSUE TITLE
Throws exception when attempting to provision via vagrant

### ISSUE THREAD

**Issue by senguttuvang** [rivaros/ansible-playbook-shim#1]
==> default: Running provisioner: ansible...
"Windows Ansible Shim in Action..."

Parameters received: --user=vagrant --connection=ssh --timeout=30 --limit=default --inventory-file=C:/projects/myProject/.vagrant/provisioners/ansible/inventory playbook.yml
cp: cannot create regular file ΓÇÿ/home/SenG/.ssh/vagrant/default/private_keyΓÇÖ: Permission denied

PLAY [all] *******************************************************************\* 

GATHERING FACTS **************************************************************\* 
      2 [main] python2.7 9136 child_info_fork::abort: address space needed by '_speedups.dll' (0x510000) is already occupied
      2 [main] python2.7 5952 child_info_fork::abort: address space needed by '_speedups.dll' (0x510000) is already occupied
fatal: [default] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 62, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 551, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, become=self.become, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1174, in _low_level_exec_command
    in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 306, in exec_command
    (p, stdin) = self._run(ssh_cmd, in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 124, in _run
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable

TASK: [update apt cache] *****************************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/SenG/playbook.retry

default                    : ok=0    changed=0    unreachable=1    failed=0

**Comment by senguttuvang** [comment]
Thanks, it's a different problem. I resolved it by 

"%SYSTEMDRIVE%\Users\%USERNAME%.babun\cygwin\bin\dash.exe" -c '/usr/bin/rebaseall -v'
